### ISSUE TITLE
Breaks Manjaro

### ISSUE THREAD

**Issue by ftastisch** [linux-surface/libwacom-surface#3]
Hi,

I tried installing this on Manjaro from AUR, which removes libwacom, on the Surface Go. Somehow, I'm not able to see a graphical interface afterwards, starting one from the command line does not work either.

Did I do something wrong when removing libwacom?

BR, Fo

**Comment by qzed** [comment]
Is there anything that could be related to this in the journalctl log? This shouldn't happen by just installing libwacom-surface as desktop environments shouldn't directly depend on the presence/absence of it and should function without it as far as I know. In any case, libwacom-surface should be a drop-in replacement for libwacom (so removing it was correct).

**Comment by ftastisch** [comment]
Hi! Thanks for your quick reply. I did a fresh install and looked at what happened when installing libwacom-surface. It seems, gnome and a lot of its components are removed together with the original libwacom. Reinstalling them brings back the graphical interface, touch is still not working though. But I guess, that might be a kernel issue (currently on 5.5.6-arch1-2-surface). So I think we can close this issue.

**Comment by qzed** [comment]
That's a bit odd, since libwacom-surface has `provides=("libwacom")` set, so unless there's an explicit dependency on a specific version, installing libwacom-surface (which directly replaces libwacom) should not cause any dependencies on libwacom to be removed. (Manually removing libwacom without installing libwacom-surface in the same package manager call will uninstall the dependents though, if not specified otherwise).

Glad you've got it fixed. Regarding the touchscreen: As far as I know, the Surface Go doesn't use IPTS but rather an [I2C touchscreen](https://github.com/linux-surface/libwacom/blob/ipts/data/surface-go.tablet#L5), so it should work on v5.5 out of the box. You could try to find that device with evtest or some other input tool. If that doesn't lead anywhere you should probably open a new issue on the [linux-surface](https://github.com/linux-surface/linux-surface) repo.
